// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTfk5-apteVuGvBVcHHibiAayPKfqAgEQ',
    appId: '1:1016775501340:web:f7f0657535309784f5e1d9',
    messagingSenderId: '1016775501340',
    projectId: 'yoripe-9975d',
    authDomain: 'yoripe-9975d.firebaseapp.com',
    storageBucket: 'yoripe-9975d.appspot.com',
    measurementId: 'G-T6DJ5MSMSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB57bLD9sA6aV3JrbS9p-AtJJmPTPb78ZM',
    appId: '1:1016775501340:android:17f8bcb819c123eaf5e1d9',
    messagingSenderId: '1016775501340',
    projectId: 'yoripe-9975d',
    storageBucket: 'yoripe-9975d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJjuiQwTWIA7JkIF3NkpS3eYzMe8Y1dhc',
    appId: '1:1016775501340:ios:57a4b5d7a57d18a0f5e1d9',
    messagingSenderId: '1016775501340',
    projectId: 'yoripe-9975d',
    storageBucket: 'yoripe-9975d.appspot.com',
    iosBundleId: 'com.tedlim.yoripe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJjuiQwTWIA7JkIF3NkpS3eYzMe8Y1dhc',
    appId: '1:1016775501340:ios:57a4b5d7a57d18a0f5e1d9',
    messagingSenderId: '1016775501340',
    projectId: 'yoripe-9975d',
    storageBucket: 'yoripe-9975d.appspot.com',
    iosBundleId: 'com.tedlim.yoripe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTfk5-apteVuGvBVcHHibiAayPKfqAgEQ',
    appId: '1:1016775501340:web:94fb4d3de8fae0eff5e1d9',
    messagingSenderId: '1016775501340',
    projectId: 'yoripe-9975d',
    authDomain: 'yoripe-9975d.firebaseapp.com',
    storageBucket: 'yoripe-9975d.appspot.com',
    measurementId: 'G-9VBV14RE1K',
  );
}
